# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_kegg.ipynb.

# %% auto 0
__all__ = ['get_kegg_species_list', 'mkdf_kegg_species_list', 'download_kegg_gene', 'read_kegg_gene',
           'get_parsed_kegg_gene_entries', 'SHOW_ME_THE_DATA', 'kegg_connections_build', 'kegg_connections_clean',
           'kegg_connections_append_y_hat', 'kegg_connections_sanitize_names']

# %% ../nbs/05_kegg.ipynb 5
# Get all the genes for zea mays
# Some gene entries that don't start begin with a chromosome number. These included plastid (Pltd) and mitochondria (MT) genes.

def get_kegg_species_list(species = 'zma'):
    import os
    import requests
    from sparsevnn.qol import ensure_dir_path_exists
    # make sure the directory exists to hold these data
    ensure_dir_path_exists(dir_path = '../data_ext/'+species+'/kegg')

    file_path = '../data_ext/'+species+'/kegg'+'/'+species+'_list.txt'
    # only retrieve if there isn't a local copy
    if file_path.split('/')[-1] in os.listdir('/'.join(file_path.split('/')[:-1])):
        with open(file_path, 'r') as f:
            r_text = f.read()
    else:
        r = requests.get('https://rest.kegg.jp/list/'+species)
        r_text = r.text
        with open(file_path, 'a') as f:
            f.write(r_text)
    return(r_text)

# %% ../nbs/05_kegg.ipynb 6
def mkdf_kegg_species_list(kegg_species_list):
    import pandas as pd
    kegg_list_zma = pd.DataFrame([e.split('\t') for e in kegg_species_list.split('\n') ])
    # clean up names
    kegg_list_zma = kegg_list_zma.rename(columns = dict(zip(
        [i for i in range(4)],
        ['gene', 'seq_type', 'chromosome_positon', 'gene_type']
    )))

    kegg_list_zma = kegg_list_zma.loc[kegg_list_zma.chromosome_positon.notna(), ]
    return(kegg_list_zma)

# %% ../nbs/05_kegg.ipynb 12
def download_kegg_gene(kegg_gene = 'zma:103644366', **kwargs):    
    """
    Downloads kegg gene entry if it does not exist locally. 
    Can optionally take a numeric value as `sleep_for` to sleep after downloading a file. 
    Useful for controlling the rate requests being sent to the API.
    """
    from tqdm import tqdm
    from sparsevnn.qol import ensure_dir_path_exists
    species = kegg_gene.split(':')[0]
    dir_path = '../data_ext/'+species+'/kegg/gene_entries/'
    ensure_dir_path_exists(dir_path = dir_path)
    
    kegg_gene_safename = kegg_gene.replace(':', '_') # name that's safe for file names
    file_path = dir_path+kegg_gene_safename+'.txt'
    
    # only download if the file doesn't already exist
    if os.path.exists(file_path):
        pass
    else:
        # option to sleep for a given amount of time so tha tthe api isn't accessed to much
        # sleeping here means that we only sleep if there will be a request to download
        if 'sleep_for' in kwargs.keys():
            time.sleep(kwargs['sleep_for'])
        
        r = requests.get('https://rest.kegg.jp/get/'+kegg_gene)
        with open(file_path, 'a') as f:
            f.write(r.text)

# %% ../nbs/05_kegg.ipynb 13
def read_kegg_gene(
    kegg_gene = 'zma:103644366',
    **kwargs # Intended to allow for explicit 'encoding' to be passed into open the file : encoding="ISO-8859-1"
    ):  
    "Reads in locally cached KEGG gene entries. Will download the requested entry if it doesn't exist locally."
    import os
    species = kegg_gene.split(':')[0]
    dir_path = '../data_ext/'+species+'/kegg/gene_entries/'
    ensure_dir_path_exists(dir_path = dir_path)
    
    kegg_gene_safename = kegg_gene.replace(':', '_') # name that's safe for file names
    file_path = dir_path+kegg_gene_safename+'.txt'

    if not os.path.exists(file_path):
        download_kegg_gene(kegg_gene)
    
    if 'encoding' in kwargs.keys():
        with open(file_path, encoding  = kwargs['encoding']) as f:
            r_text = f.read()        
    else:
        with open(file_path) as f:
            r_text = f.read()
            
    return(r_text)

# %% ../nbs/05_kegg.ipynb 82
def get_parsed_kegg_gene_entries(species = 'zma'):
    from sparsevnn.qol import ensure_dir_path_exists
    from tqdm import tqdm
    import os
    "This is a wrapper function that should provide a function that will download a species data or provide it if it has been downloaded."
    ## Download kegg entries if genes have not been cached ====
    kegg_list = get_kegg_species_list(species = species)
    kegg_list = mkdf_kegg_species_list(kegg_species_list = kegg_list)

    print('Checking that genes are downloaded...')
    for kegg_gene in tqdm(kegg_list.gene):
        try:
            download_kegg_gene(kegg_gene = kegg_gene, sleep_for = np.random.uniform(0.5, 1.5)* 1.2 )  
        except:
            print('Problem with '+kegg_gene) 


    ## Combine gene entries ====
    save_dir = f'../data_ext/{species}/kegg/'
    save_path = save_dir+'cached_kegg_gene_files.pkl'

    ensure_dir_path_exists(dir_path = save_dir)

    if not os.path.exists(save_path):
        print('Preparing and pickling genes entries...')
        # This is a pain. I would like to parallelize reading these files in, but since it only has to be done once per species doing so would be premature optimization.
        # BUT it seems that nbdev is rerunning it as part of the CI workflow. So caching it makes sense. 
        kegg_gene_files = os.listdir(f'{save_dir}/gene_entries/')
        kegg_gene_entries = [kegg_gene_to_dict(
            kegg_file = kegg_gene_file,
            encoding="ISO-8859-1"
        ) for kegg_gene_file in kegg_gene_files]

        with open(save_path, 'wb') as handle:
            pkl.dump(kegg_gene_entries, 
                    handle, 
                    protocol=pkl.HIGHEST_PROTOCOL)
    else:
        print('Loading pickled genes entries...')
        # Reading in data
        with open(save_path, 'rb') as handle:
            kegg_gene_entries = pkl.load(handle)


    ## Parsing and pickle gene entries ====
    save_dir = f'../data/{species}/kegg/'
    save_path = save_dir+'kegg_gene_entries.pkl'
    ensure_dir_path_exists(dir_path = save_dir)

    if not os.path.exists(save_path):
        print('Parsing and pickling genes entries...')
        parsed_kegg_gene_entries = [parse_kegg_gene_entry(
            kegg_gene_entry = kegg_gene_entry
            ) for kegg_gene_entry in kegg_gene_entries]

        with open(save_path, 'wb') as handle:
            pkl.dump(parsed_kegg_gene_entries, 
                    handle, 
                    protocol=pkl.HIGHEST_PROTOCOL)
    else: 
        print('Loading parsed and pickled genes entries...')
        # Reading in data
        with open(save_path, 'rb') as handle:
            kegg_gene_entries = pkl.load(handle)
    
    return kegg_gene_entries

# %% ../nbs/05_kegg.ipynb 84
def SHOW_ME_THE_DATA():
    import pkgutil
    import json
    xx = pkgutil.get_data('sparsevnn', 'test_data/cached_kegg_gene_files.json')
    xx2 = json.loads(xx.decode())
    return xx2


# %% ../nbs/05_kegg.ipynb 163
# LOD is list of dicts.
# def kegg_brite_LOD_to_connections(
def kegg_connections_build(
        n_genes, 
        kegg_gene_brite):
    """
    The goal here is to have a dict with each node and a list of it's children. 
    For example, the graph
    a--b--d
    |-c--e
    Would be parsed into     
    {'a':['b', 'c'],
    'b':['d'],
    'c':['e']}
    """
    kegg_connections = {}
    # for all genes in list
    for i in range(n_genes): 
        temp = kegg_gene_brite[i]['BRITE']['BRITE_PATHS']
        # clean up to make sure that there are no ":" characters. These can mess up graphviz
        temp = [[temp[j][i].replace(':', '-') for i in range(len(temp[j])) ] for j in range(len(temp))]
        # all paths through graph associated with a gene
        for j in range(len(temp)):
            # steps of the path through the graph
            for k in range(len(temp[j])-1):
                
                # name standardization 
                temp_jk  = temp[j][k]
                temp_jk1 = temp[j][k+1]
                temp_jk  = temp_jk.lower().title().replace(' ', '')
                temp_jk1 = temp_jk1.lower().title().replace(' ', '')
                
                # if this is a new key, add it and add the k+1 entry as it's child
                if temp_jk  not in kegg_connections.keys():
                    kegg_connections[temp_jk] = [temp_jk1]
                else: 
                    # Check to see if there's a new child to add   
                    if temp_jk1 not in kegg_connections[temp_jk]:
                        # make sure that no key contains itself. This was a problem for 'Others' which is now disallowed.
                        if (temp_jk != temp_jk1):
                            # add it.
                            kegg_connections[temp_jk].extend([temp_jk1])
    return(kegg_connections)          


# %% ../nbs/05_kegg.ipynb 164
def kegg_connections_clean(kegg_connections):
    if 'Others' in kegg_connections.keys():
        del kegg_connections['Others']
        print('Removed node "Others"')

    # remove 'Others' as a possible value
    for key in kegg_connections.keys():
        kegg_connections[key] = [e for e in kegg_connections[key] if e != 'Others']

    # Make sure that no list contains it's own key
    for key in kegg_connections.keys():
        kegg_connections[key] = [e for e in kegg_connections[key] if e != key]

    # there might be associations with no dependants and with no dependants except those that have no dependants.
    # Build up a list with those keys that don't connect back to snps then I'll pass over the connection dict once to remove references to them.
    rm_list = []
    rm_list_i = len(rm_list)
    rm_list_j = -1
    for i in range(100):
        if rm_list_i == rm_list_j:
            break
        else:
            rm_list = [key for key in kegg_connections.keys() if [e for e in kegg_connections[key] if e not in rm_list] == []]
            rm_list_j = rm_list_i 
            rm_list_i = len(rm_list)
    # rm_list

    for key in rm_list:
        del kegg_connections[key]
        
    for key in kegg_connections.keys():
        kegg_connections[key] = [e for e in kegg_connections[key] if e not in rm_list]
    return kegg_connections

# %% ../nbs/05_kegg.ipynb 165
def kegg_connections_append_y_hat(kegg_connections):
    # add yhat node to the graph
    temp_values = []
    for key in kegg_connections.keys():
        temp_values += kegg_connections[key]

    kegg_connections['y_hat'] = [key for key in kegg_connections.keys() if key not in temp_values]
    return kegg_connections

# %% ../nbs/05_kegg.ipynb 166
def kegg_connections_append_y_hat(kegg_connections):
    # add yhat node to the graph
    temp_values = []
    for key in kegg_connections.keys():
        temp_values += kegg_connections[key]

    kegg_connections['y_hat'] = [key for key in kegg_connections.keys() if key not in temp_values]
    return kegg_connections

# %% ../nbs/05_kegg.ipynb 168
def kegg_connections_sanitize_names(kegg_connections, replace_chars = {'.':'_'}):
    # have to clean the key values so that none have '.' because I'm looking up nodes by name and pytorch doesn't allow this.
    #NOTE this will potentially (but not here) create a bug if there are genes named with '.'    

    def replace_select_chars(in_str, replace_chars):
        for key in replace_chars.keys():
            in_str = in_str.replace(key, replace_chars[key])
        return in_str

    new_kegg_connections = {}
    for key in kegg_connections.keys():
        new_kegg_connections[replace_select_chars(in_str = key, replace_chars=replace_chars)] = [replace_select_chars(in_str = e, replace_chars=replace_chars) for e in kegg_connections[key]]

    return new_kegg_connections
